# Copyright 2026 INL Dynamics / Complexity-ML. All rights reserved.
# Licensed under CC-BY-NC-4.0
"""
Export Conversation — Save a coding session as markdown or JSON.

Usage:
    from agent_bmm.coder.export import export_session

    export_session(history, "session.md", fmt="markdown")
    export_session(history, "session.json", fmt="json")
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path


def export_session(
    history: list[dict[str, str]],
    output_path: str | Path,
    fmt: str = "markdown",
    metadata: dict | None = None,
) -> str:
    """
    Export a conversation history to a file.

    Args:
        history: List of {"role": ..., "content": ...} messages.
        output_path: Output file path.
        fmt: "markdown" or "json".
        metadata: Optional metadata (model, tokens, cost, etc.).

    Returns:
        Path to the exported file.
    """
    output = Path(output_path)

    if fmt == "json":
        data = {
            "exported_at": datetime.now().isoformat(),
            "metadata": metadata or {},
            "messages": history,
        }
        output.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    else:
        output.write_text(_to_markdown(history, metadata))

    return str(output)


def _to_markdown(history: list[dict[str, str]], metadata: dict | None = None) -> str:
    """Convert conversation history to markdown."""
    lines = ["# Agent BMM Session\n"]
    lines.append(f"*Exported: {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n")

    if metadata:
        lines.append("## Metadata\n")
        for key, value in metadata.items():
            lines.append(f"- **{key}**: {value}")
        lines.append("")

    lines.append("## Conversation\n")

    for msg in history:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")

        if role == "system":
            lines.append("<details><summary>System prompt</summary>\n")
            lines.append(f"```\n{content[:500]}\n```\n")
            lines.append("</details>\n")
        elif role == "user":
            # Check if it's a result or a user query
            if content.startswith("Result:\n"):
                lines.append(f"**Result:**\n```\n{content[8:500]}\n```\n")
            else:
                lines.append(f"### User\n\n{content}\n")
        elif role == "assistant":
            lines.append(f"### Agent\n\n```json\n{content[:1000]}\n```\n")

    lines.append("---\n*Generated by [Agent BMM](https://github.com/Complexity-ML/agent_bmm)*")
    return "\n".join(lines)
